version: '3.7'

services:
  php_fpm:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/
    container_name: leru_php_fpm
    volumes:
      - leru-volume:/var/www
    networks:
      - default

  crudm:
    image: nginx:latest
    container_name: leru_nginx
    networks:
      - default
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - leru-volume:/var/www/
    depends_on:
      - php_fpm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crudm.rule=Host(`license.cards`) && PathPrefix(`/crudm`)"
      - "traefik.http.routers.crudm.middlewares=crudm-stripprefix"
      - "traefik.http.middlewares.crudm-stripprefix.stripprefix.prefixes=/crudm"
      - "traefik.http.routers.crudm.tls=true"
      - "traefik.http.routers.crudm.tls.certresolver=resolver"
    expose:
      - 8000

networks:
  default:
    external:
      name: external-example
volumes:
  leru-volume:

